### PR TITLE
Bug/bug 61554

### PR DESCRIPTION
**Pull request by vrojastpr**
#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

FFInputEmail & FFInputPhone accept "required" attribute

#### Reviewers should focus on:

Before the "required" attribute was depending on the existence of a "validate" function being passed as props.
Which was overriding the value from "required" when specified. 
For this reason the "optional" text was not being correctly shown when needed.

### CODE REVIEW

**Review by sussexrick — COMMENTED** [review]
What's the reason for changing back to 'phone'? If the need is to suppress browser validation then adding a `novalidate="novalidate"` attribute should do the job. If we really can't use 'tel' for some reason we should be using 'text' rather than making up our own invalid value for 'type'.

**Comment by vrojastpr** [comment]
> What's the reason for changing back to 'phone'? If the need is to suppress browser validation then adding a `novalidate="novalidate"` attribute should do the job. If we really can't use 'tel' for some reason we should be using 'text' rather than making up our own invalid value for 'type'.

I was just trying to see if that was the reason for the test fails in circle-ci, because locally they are working fine.
I will try to use the "novalidate" attribute to see if that can be the reason, but not sure if that will make something being specified in an input, usually that attribute is applied to the "form" tag.

**Comment by sussexrick** [comment]
You were right about `novalidate` being an attribute of the form element, so it doesn't make sense to add it to the fields here.

Setting the `required` prop sets a `required` attribute on the HTML input, which would trigger browser validation. But if browser validation is turned off using `novalidate` on the form, is there JS here that steps in and does the validation?

**Comment by vrojastpr** [comment]
> You were right about `novalidate` being an attribute of the form element, so it doesn't make sense to add it to the fields here.
> 
> Setting the `required` prop sets a `required` attribute on the HTML input, which would trigger browser validation. But if browser validation is turned off using `novalidate` on the form, is there JS here that steps in and does the validation?

Yes, `FFInputEmail` will always call `isEmailValid`via the `validate` prop of `<Field>`. And the same for `FFInputPhone `which calls `isPhoneValid`.

**Review by sussexrick — APPROVED** [review]

**Pull request merged**
