### PR TITLE
AB#106672 add aria-live attribute

### PR DESCRIPTION
**Pull request by dotcom9**
Add aria-live attribute

### CODE REVIEW

**Comment by sussexrick** [comment]
@dotcom9 This is not making any difference to NVDA output. I'm having a play with different options...

**Comment by sussexrick** [comment]
@dotcom9 It doesn't work because the aria-live region needs to exist before and after the change of context, which means it needs to be in `addressLookup.tsx`. Adding it to the child components means it disappears and a new one appears with each change of context, which doesn't work.

You could enclose the whole component in an aria-live region, but then NVDA reads out everything that just appeared without saying what's text, what's a button etc. I think the following solution is preferable, which just announces the new view that's appeared with the keyboard focus in the right place:

```jsx
<div aria-live="polite" class={accessibilityStyles.visuallyHidden}>
  {addressView === AddressView.PostcodeLookup && 'Postcode lookup'}
  {addressView === AddressView.SelectAddress && 'Select address'}
  {addressView === AddressView.EditAddress && 'Address selected'}
</div>
```

SaveAndContinue.tsx has an example of the import for the style, and obviously the text should be editable.

**Comment by dotcom9** [comment]
@sussexrick I don't think the visually hidden style hides the content of the div (ie the form views) and is really redundant so I have left it out.

**Comment by sussexrick** [comment]
@dotcom9 I've just emailed the accessibility tester for an opinion on this - is it better to read out the whole component or just announce the new context?

**Review by bentpr — APPROVED** [review]

**Pull request merged**
