### PR TITLE
Feature/88254 trustee card redesign

### PR DESCRIPTION
**Pull request by tapiwamukwewa**
#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

- Trustee card displays sub heading when address and contact details sections are opened
- Chevron is now right aligned
- Cancel link to close an open section is added next to the Save and Continue button

### CODE REVIEW

**Review by dotcom9 — APPROVED** [review]

**Comment by dotcom9** [comment]
Worth tidying up the issues raised by SonarCloud.

**Review by HarryAmmon — CHANGES_REQUESTED** [review]
When running this branch locally the following cards do not behave as expected when pressing the 'cancel' button:
- Actuary
- Corporate Group Trustee
- InHouse

**Review by sussexrick — CHANGES_REQUESTED** [review]
When running this branch locally and testing the trustee card as an example, using NVDA it does not give the user the feedback they need. If I tab to 'Correspondence address' it says "Correspondence address button collapsed", which is correct. If I press enter to trigger the button is should then say "expanded", but it's silent. The keyboard should stay on the button but it doesn't, and that's probably why it's silent. The same problem occurs with the 'Save and close' button - it should announce that the section is collapsed, but it's silent.

**Comment by vrojastpr** [comment]
I believe we should display the subheading in all cards and not just the Trustee card. All cards should have the same behavior. Otherwise it will solve that bug but then a new one will be created for the employers and other service providers.

**Comment by vrojastpr** [comment]
@tapiwamukwewa After running `yarn test`, prettier format is applied, you should commit those changes too. 
Otherwise those changes will keep appearing for the next changes which might have nothing to do with the files modified in this PR.

**Review by bentpr — APPROVED** [review]

**Review by dotcom9 — APPROVED** [review]

**Pull request merged**
